package com.company.pdfmerge.common.error;

public enum MergeErrorCode {
    MERGE_400_PDF_INVALID,
    MERGE_400_FILE_TOO_LARGE,
    MERGE_400_TOO_MANY_FILES,
    MERGE_400_TOTAL_TOO_LARGE,
    MERGE_400_ENCRYPTED_UNSUPPORTED,
    MERGE_422_PDF_CORRUPTED,
    MERGE_503_ENGINE_FAILED,
    MERGE_504_TIMEOUT,
    MERGE_599_NETWORK
}
