spring:
  application:
    name: pdf-merge-worker
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pdf_toolkit?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: change_me
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3s
server:
  port: 0
pdfmerge:
  storage:
    root-dir: /data/pdf-merge
  queue:
    stream-key: stream:pdf:merge:task
    dlq-stream-key: stream:pdf:merge:task:dlq
    consumer-group: merge_worker_group
    consumer-name: worker-local
    read-count: 10
    block-ms: 2000
    max-retry: 2
